package sakila.entity;
// Generated Nov 11, 2018 10:31:11 PM by Hibernate Tools 4.3.1



/**
 * Bookings generated by hbm2java
 */
public class Bookings  implements java.io.Serializable {


     private int id;
     private String firstname;
     private String lastname;

    public Bookings() {
    }

	
    public Bookings(int id) {
        this.id = id;
    }
    public Bookings(int id, String firstname, String lastname) {
       this.id = id;
       this.firstname = firstname;
       this.lastname = lastname;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getFirstname() {
        return this.firstname;
    }
    
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }




}


